install:
	install -d $(DESTDIR)/etc/qubes-rpc
	install -m 0644 qubes.DeadMansSwitch $(DESTDIR)/etc/qubes-rpc
	install -m 0664 -D policy/qubes.DeadMansSwitch \
		$(DESTDIR)/etc/qubes-rpc/policy/qubes.DeadMansSwitch

